Las siguientes líneas son para **indicar mediante un comentario el tema del notebook (crear un DataFrame a partir de una lista) e importar la librería pandas**.

In [ ]:
# Create dataframe from a list

import pandas as pd

La siguiente línea es para **crear una lista simple de números**.

In [ ]:
numbers = [1, 2, 3, 4, 5, 6]

La siguiente línea es para **crear un DataFrame de pandas a partir de la lista de números**.

In [ ]:
pd.DataFrame(numbers)

   0
0  1
1  2
2  3
3  4
4  5
5  6

La siguiente línea es para **crear una lista de listas, donde cada sublista representa una fila con nombre y edad**.

In [ ]:
data = [["Jhon",  23], ["Mary", 18], ["Jhon", 31]]

La siguiente línea es para **crear un DataFrame de pandas a partir de la lista de listas**.

In [ ]:
pd.DataFrame(data)

      0   1
0  Jhon  23
1  Mary  18
2  Jhon  31

La siguiente línea es para **crear el DataFrame indicando los nombres de las columnas ("name" y "age")**.

In [ ]:
pd.DataFrame(data, columns = ["name", "age"])

   name  age
0  Jhon   23
1  Mary   18
2  Jhon   31

La siguiente línea es para **crear el DataFrame indicando tanto los nombres de las columnas como un índice personalizado (id1, id2, id3)**.

In [ ]:
pd.DataFrame(data, columns = ["name", "age"], index = ["id1", "id2", "id3"])

     name  age
id1  Jhon   23
id2  Mary   18
id3  Jhon   31